#!/bin/bash
clear
echo "NutChain SaberMod 5.4 R08/16 SN"
echo "Setting up toolchain for use"
rm -rf .git
cd libexec/gcc/x86_64-linux-gnu/5.4.1
echo "******[You must have tar & cat installed to make this TC useable]******"
echo "Rebuilding tarfile"
cat execlib* > execlib.tar.xz
echo "Untaring Files"
tar -axvf execlib.tar.xz
echo "Removing Temp files"
rm -f execlib*
echo "all done"
echo " "
echo " "
echo "use these export commands now"
echo " "
echo "export ARCH=x86_64"
echo "export CCOMPILE=$CROSS_COMPILE"
echo "export CROSS_COMPILE=x86_64-linux-"
echo " "
echo " "
echo "Happy compiling :) "
echo "Script by @say99 & Adopted by the apprentice @nutcasev1.5"
