#!/bin/bash
clear
echo "NutChain Linaro 6.1 R07/16 SN"
echo "Setting up toolchain for use"
cd libexec/gcc/x86_64-linux-gnu/6.1.1
echo "untar files"
echo "******[You must have tar & cat installed to make this TC useable]******"
tar -axvf exec.tar.xz
echo "Removing Temp files"
rm -f exec.tar.xz
echo "all done"
echo " "
echo " "
echo "use these export commands now"
echo " "
echo "export ARCH=x86_64"
echo "export CCOMPILE=$CROSS_COMPILE"
echo "export CROSS_COMPILE=x86_64-linux-gnu-"
echo " "
echo " "
echo "Happy compiling :) "
echo "Script by @say99 & Adopted by the apprentice @nutcasev1.5"